"""add session lifecycle fields and transcript_turns table

Revision ID: 63e992aaea9d
Revises: a80ba7e1eba8
Create Date: 2026-06-17 14:14:53.746049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63e992aaea9d'
down_revision: Union[str, Sequence[str], None] = 'a80ba7e1eba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcript_turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('speaker_type', sa.Enum('PANELIST', 'USER', name='speakertype'), nullable=False),
    sa.Column('panelist_id', sa.String(length=64), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('started_at_ms', sa.Integer(), nullable=False),
    sa.Column('ended_at_ms', sa.Integer(), nullable=False),
    sa.Column('gesture_sequence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_followup', sa.Boolean(), nullable=False),
    sa.Column('targets_weakness', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'sequence', name='uq_transcript_turns_session_sequence')
    )
    op.create_index(op.f('ix_transcript_turns_session_id'), 'transcript_turns', ['session_id'], unique=False)
    session_status_enum = postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='sessionstatus')
    session_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('sessions', sa.Column('status', session_status_enum, nullable=False, server_default='PENDING'))
    op.add_column('sessions', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sessions', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sessions', sa.Column('question_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'question_count')
    op.drop_column('sessions', 'ended_at')
    op.drop_column('sessions', 'started_at')
    op.drop_column('sessions', 'status')
    postgresql.ENUM(name='sessionstatus').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_transcript_turns_session_id'), table_name='transcript_turns')
    op.drop_table('transcript_turns')
    # ### end Alembic commands ###
