"""create sessions table

Revision ID: a80ba7e1eba8
Revises: eae9fc21b0b5
Create Date: 2026-06-17 12:05:15.749989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a80ba7e1eba8'
down_revision: Union[str, Sequence[str], None] = 'eae9fc21b0b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scenario', sa.Enum('TUTORIAL_PRACTICE', 'PRESENTATION', 'PROJECT_DEFENSE', 'ORAL_EXAMINATION', 'SEMINAR_DEFENSE', 'ENGLISH_PROFICIENCY', name='scenariotype'), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=False),
    sa.Column('document_id', sa.String(length=255), nullable=True),
    sa.Column('panelists', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('real_time_feedback', sa.Boolean(), nullable=False),
    sa.Column('answer_timer', sa.Boolean(), nullable=False),
    sa.Column('save_transcript', sa.Boolean(), nullable=False),
    sa.Column('clarity', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('structure', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
